### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by pavelpp** [rollbar/terraform-provider-rollbar#361] opened 2023-05-05 10:22 UTC
I'm creating project tokens using for_each statement and seeing this error upon running apply after the first token is created. 
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.rollbar.rollbar_project_access_token.project_token["token_1"], provider
│ "module.rollbar.provider[\"registry.terraform.io/rollbar/rollbar\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

Worth noting that it passed on second apply and created remaining 2 tokens

OS: MacOs 12.5.1
HW: Apple Silicon
Provider version: 1.12.0

Terraform v1.3.7 on darwin_arm64

**Comment by rollbar-bborsits** [comment] 2023-05-18 10:58
Hey, @pavelpp @jtsaito,
Thanks for reporting this issue. As it is a duplicate of https://github.com/rollbar/terraform-provider-rollbar/issues/359, I close this ticket.
Let's keep all communication in that thread.
Cheers,
@rollbar-bborsits

**Closed** 2023-05-18 10:58 UTC

**Comment by jtsaito** [comment] 2026-02-26 09:54
@ghost can you re-open 

> Hey, [@pavelpp](https://github.com/pavelpp) [@jtsaito](https://github.com/jtsaito), Thanks for reporting this issue. As it is a duplicate of [#359](https://github.com/rollbar/terraform-provider-rollbar/issues/359), I close this ticket. Let's keep all communication in that thread. Cheers, @rollbar-bborsits

Can you re-open https://github.com/rollbar/terraform-provider-rollbar/issues/359?
